### ISSUE TITLE
Hvordan går det - skal vi mødes?

### ISSUE THREAD

**Issue by lakruzz** [ttc-classroom/pydevx-lindjacob#18]
Hej @lindjacob 

Hvordan går det, jeg kan se at du er travlt optaget af vores tutorial. Det ser godt ud 💪!

Jeg er ved at være igennem en række interviews med kandidater og jeg vil meget gerne ha dig med videre i vores forløb.

Så jeg vil gerne have at vi mødes i en lidt mere formel setting, hvor vores Talent Attraction (TA) kommer med ind over, de har nogle helt andre tests (de er faktisk også sjove!) og de vil sætte møder op med, så du også kan møde nogle af vores kollegaer. Vi kan også gå tage en snak om nogle af de udfordringer en opgave som den her har budt på.

Har du stadig lyst til det?

Lars Kruse
20 87 25 30

**Comment by lindjacob** [comment]
Hej Lars!

Tak, jeg vil gerne lave de sidste udfordringer også 😊 De er rigtig interessante for mig og jeg er vild med måden de er skrevet på.

Fedt at du vil snakke mere, det vil jeg også rigtig gerne 👏 Jeg vil glæde mig til de næste tests.

Vi kan snakke sammen i aften eller i morgen alt efter hvad der passer dig?

**Comment by lindjacob** [comment]
Du er så behagelig at snakke med Lars 😊
Her er mine oplysninger:

Jacob Lind
Langelandsgade 12, 4. th.
8000 Aarhus C
21221945
contact@jacoblind.me

**Comment by lakruzz** [comment]
Hej Jacob

Jeg har sendt en besked til TA at de skal række ud til dig. Måske går der lige nogle dage, jeg fik et auto reply at de er tyndt besat her i juli...

**Comment by lindjacob** [comment]
Hej Lars,

Fedt at høre. Jeg forstår.
Jeg venter bare på dem 😊
